<template>
<div class="games-box-content" data-module="game-box" data-mode="standard" style="height: auto;"><div class="games-box-placeholder" style="display: none;"><div class="games-box-placeholder-image"><picture><source srcset="https://static.casino.guru/pict/193217/European-Roullette-Pro.jpg?timestamp=1653450428000&amp;width=838&amp;imageDataId=221673&amp;webp=true&amp;compressWebp=85" type="image/webp"><img src="https://static.casino.guru/pict/193217/European-Roullette-Pro.jpg?timestamp=1653450428000&amp;width=838&amp;imageDataId=221673" alt="European Roullette Pro.jpg"></picture></div><div class="btn-wrapper"><span id="game_link" class="games-box-btn-main js-games-box-btn-main" data-url="https://asccw.playngonetwork.com/Casino/IframedView?pid=2&amp;gid=europeanroulette&amp;lang=en_US&amp;practice=1&amp;channel=desktop&amp;div=flashobject&amp;width=100%25&amp;height=100%25&amp;user=&amp;password=&amp;ctx=&amp;demo=2&amp;brand=&amp;lobby=&amp;rccurrentsessiontime=0&amp;rcintervaltime=0&amp;rcaccounthistoryurl=&amp;rccontinueurl=&amp;rcexiturl=&amp;rchistoryurlmode=&amp;autoplaylimits=0&amp;autoplayreset=0&amp;callback=flashCallback&amp;rcmga=&amp;resourcelevel=0&amp;hasjackpots=False&amp;country=&amp;pauseplay=&amp;playlimit=&amp;selftest=&amp;sessiontime=&amp;coreweburl=https://asccw.playngonetwork.com/&amp;showpoweredby=True" data-fallback-url="/gameDetailIos?gameId=12641" data-open-in-new-tab="false" data-requireflash="false" data-ga-id="gamDet_top_btn_play" data-ga-param="12641"><span class="icon-wrapper"><svg width="20" height="20" class="c-white"><use xlink:href="#base_ui_ico_play_mark"></use></svg></span><span class="text"><strong>Play for Free</strong><small>100% free / No limits</small></span></span><div class="games-box-btn-secondary js-playforreal-button-container" data-userscore-click-target="" data-ga-id="gamDet_top_btn_playForReal" data-ga-param="12641"><svg width="20" height="20" class="c-white mr-s"><use xlink:href="#base_ui_ico_money"></use></svg>
                                        Play for Real Money
                                    </div></div></div><div class="games-box-game" style="height: 410px; display: block;"><div class="iframe-wrapper" style="width:100%;height:100%;"><iframe src="https://asccw.playngonetwork.com/Casino/IframedView?pid=2&amp;gid=europeanroulette&amp;lang=en_US&amp;practice=1&amp;channel=desktop&amp;div=flashobject&amp;width=100%25&amp;height=100%25&amp;user=&amp;password=&amp;ctx=&amp;demo=2&amp;brand=&amp;lobby=&amp;rccurrentsessiontime=0&amp;rcintervaltime=0&amp;rcaccounthistoryurl=&amp;rccontinueurl=&amp;rcexiturl=&amp;rchistoryurlmode=&amp;autoplaylimits=0&amp;autoplayreset=0&amp;callback=flashCallback&amp;rcmga=&amp;resourcelevel=0&amp;hasjackpots=False&amp;country=&amp;pauseplay=&amp;playlimit=&amp;selftest=&amp;sessiontime=&amp;coreweburl=https://asccw.playngonetwork.com/&amp;showpoweredby=True" frameborder="0" id="gamefileEmbed1" scrolling="no"></iframe></div></div></div>
</template>

<style>
.games-box-content .live-stream-video, .games-box-content iframe {
    display: block;
    height: 100%;
    margin: auto;
    width: 100%;
}
</style>